### ISSUE TITLE
stopped working after upgrade

### ISSUE THREAD

**Issue by Mebus** [spjoe/mopidy-ircontrol#2]
Hallo,

my mopidy-ircontrol suddenly stoppend working after an apt-get upgrade.  The command "irw" reports the correct codes when I press the buttons on my remote. Also the mopidy config looks  ok:

<code>
[IRControl]
enabled = true
#look at your lircd.conf (/etc/lirc/lircd.conf) to find you configured buttons names
mute = KEY_MUTE
next = KEY_NEXT
previous = KEY_PREVIOUS
playpause = KEY_PLAY
stop = KEY_STOP
volumeup = KEY_VOLUMEUP
volumedown = KEY_VOLUMEDOWN
</code>

How can I debug this?

Mebus

**Comment by spjoe** [comment]
add to your mopidy config (/etc/mopidy/mopidy.conf) the following:
```
[loglevels]
mopidy_IRControl = debug
```
then you should see if the received commands can be mapped to a actual mopidy command.

**Comment by spjoe** [comment]
also start mopidy with  
```
mopidy --save-debug-log
```
and then you can filt by IRControl. Here you can see if the extension is correctly discovered.

**Comment by Mebus** [comment]
Hallo,
thanks for the reply. This is the error I found:

<code>
2015-10-02 15:51:30,434 ERROR [2597:MainThread] mopidy.__main__: Extension IRControl failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 145, in main
    extension.setup(registry)
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_IRControl-0.1.0-py2.7.egg/mopidy_IRControl/__init__.py", line 54, in setup
    from .actor import IRControlFrontend
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_IRControl-0.1.0-py2.7.egg/mopidy_IRControl/actor.py", line 9, in <module>
    from mopidy.utils import process
ImportError: No module named utils
</code>

How can I fix this?

Mebus

**Comment by jodal** [comment]
Mopidy-IRControl tries to use the `mopidy.utils` package which is internal to Mopidy core. In Mopidy 1.1 it was renamed from `mopidy.utils` to `mopidy.internal` to make this clearer. Mopidy-IRControl needs to be updated to not use this package.

**Comment by Mebus** [comment]
Hi!

I fixed this manually on my raspberry pi as in my pull request:
https://github.com/spjoe/mopidy-ircontrol/pull/4
and it works now!

Thanks!

Mebus

**Comment by jodal** [comment]
It works, but it's the entirely wrong solution. "internal" means that it is internal to Mopidy core. It should be used by anyone else, and can break in any Mopidy release.

**Comment by spjoe** [comment]
When you have time, please try also my solution (master branch), unfortunately I cannot test it currently with a real setup. Just all tests are ok again. 

This is the commit doing the change 0332209

**Comment by Mebus** [comment]
I think there is still a bug, although my remote is working again:

```
2015-10-03 09:30:36,734 ERROR [3868:IRControlFrontend-14] pykka: Unhandled exception in IRControlFrontend (urn:uuid:0d230827-81f2-4b92-84fb-29ae17ebcdf1):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/core/listener.py", line 34, in on_event
    getattr(self, event)(**kwargs)
AttributeError: 'IRControlFrontend' object has no attribute 'IRButtonPressed'
2015-10-03 09:30:36,766 ERROR [3868:MpdFrontend-16] pykka: Unhandled exception in MpdFrontend (urn:uuid:aa8537b5-7588-4214-8ded-2b8b94060998):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/core/listener.py", line 34, in on_event
    getattr(self, event)(**kwargs)
AttributeError: 'MpdFrontend' object has no attribute 'IRButtonPressed'
2015-10-03 09:30:36,815 ERROR [3868:IRControlFrontend-14] pykka: Unhandled exception in IRControlFrontend (urn:uuid:0d230827-81f2-4b92-84fb-29ae17ebcdf1):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 213, in _actor_loop
    self.on_failure(*sys.exc_info())
TypeError: on_failure() takes exactly 1 argument (4 given)
```

Mebus

**Comment by spjoe** [comment]
The released version 0.1.0 does work with mopidy 1.1.1.
